### ISSUE TITLE
[Feature] Restore ability to inject JS into store, community, etc pages.

### ISSUE THREAD

**Issue by Plaer1** [shdwmtr/millennium#103]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

I still need it for some theme-specific features, for example; 
I'm pretty sure nobody but me will need a plugin that makes the background color on game pages this specific shade of gray:
![image](https://github.com/user-attachments/assets/96e82b4a-3292-4840-a2f9-73120810466f)

### Anything else?

The only alternatives I can see are:
* I make one big plugin with a lot of theme specific features that probably nobody but me would use, like a library plugin for my theme.
* Try to rebrand every feature as something other people can use (make a variable for changing the backgrounds to other hues, etc)

**Comment by shdwmtr** [comment]
Releasing now!
