### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Swaggermax1** [shdwmtr/millennium#120]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

Small Grey box with nothing inside, no theme was a problem 

### Expected Behavior

Any fix? I have no idea how to fix this or the real problem

### Steps To Reproduce

Error with theme's 

### Operating System

Windows

### Anything else?

Fix I can get some help on how to fix this that will be amazing

**Comment by shdwmtr** [comment]
It means you have no themes installed. https://docs.steambrew.app/users/getting-started#installing-themes

**Comment by Swaggermax1** [comment]
![image](https://github.com/user-attachments/assets/c5558fd3-b5d4-4099-b860-186096bd4957)

I have Theme's

**Comment by Swaggermax1** [comment]
Both Zip and file's and it still showing the grey box

**Comment by shdwmtr** [comment]
Re-read the documentation, specifically at the bottom where there is a "NOTE"
