### ISSUE TITLE
[Bug] Steam not exiting

### ISSUE THREAD

**Issue by danatationn** [shdwmtr/millennium#142]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

whenever i try exiting steam it just doesn't. after the window closes it gets stuck and doesn't fully close. i can't launch it again but it just stays in my icon tray

inspecting console logs reveals that it's trying to shut down the core plugin but it can't ? i think ?
```
STEAM [2024-10-20 11:08:48] Shutdown
STEAM [08:48.318] INFO Hooked Steam entry returned 0
STEAM [08:48.319] INFO Disconnected from [CEFBrowser] module...
STEAM [08:48.369] INFO Terminating frontend thread pool...
STEAM [08:48.370] INFO Shutting down Millennium...
STEAM [08:49.421] WARN Deconstructing 1 plugin(s) and preparing for exit...
STEAM [08:49.421] INFO Notified plugin [core] to shut down...
STEAM [08:49.421] INFO Trying to join thread 4288322381...
STEAM [08:49.421] INFO Orphaned 'core', jumping off the mutex lock...
STEAM [08:49.421] CORE Millennium-Core is unloading...
STEAM [08:49.421] INFO Shutting down plugin 'core'

```

it just gets stuck at the last line forever

after a while it eventually segfaults
`STEAM /home/bulb/.steam/steam/steam.sh: line 906: 36529 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"`

the only thing that makes it exit (except for the segfault) is running `pkill -9 steam`

### Expected Behavior

when i click the exit steam button i want it to exit after the window dissapears

### Steps To Reproduce

run arch linux kernel 6.11.4-arch1-1
run start.sh
try to quit
see results

### Operating System

Linux

### Anything else?

video of the bug in action

https://github.com/user-attachments/assets/06788252-5c0d-485b-b5e9-4925e31016de

**Comment by shdwmtr** [comment]
I'll eventually take a look into this; I don't have a linux system right now. What version of Millennium are you using?

**Comment by danatation** [comment]
the latest release, v2.12.4

**Comment by shdwmtr** [comment]
I've found the issue, and I should have it fixed in the next update!

**Comment by skyisthela** [comment]
> I've found the issue, and I should have it fixed in the next update!

Sorry for the necro but I still have the same issue

**Comment by shdwmtr** [comment]
Yeah it appears the issue has resurfaced. It will be fixed soon.

**Comment by thrailkillr** [comment]
Still happening. Damn.

**Comment by ejalxndr** [comment]
@thrailkillr Linux?

**Comment by thrailkillr** [comment]
> [@thrailkillr](https://github.com/thrailkillr) Linux?

yes.

**Comment by ejalxndr** [comment]
@thrailkillr Any logs, videos, images?

**Comment by thrailkillr** [comment]
Where are the Millennium logs stored...?

**Comment by thrailkillr** [comment]
[cef_log.txt](https://github.com/user-attachments/files/31150719/cef_log.txt)
Here's the cef log
