### ISSUE TITLE
[Bug]: Millennium does not function properly when offline

### ISSUE THREAD

**Issue by AdamRaichu** [shdwmtr/millennium#143]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

When I try to launch Steam when my wifi is turned off, Millennium does not seem to do anything (theme is disabled, plugins are not loaded, settings ui is vanilla). This does not happen when wifi is on and I am connected.

### Expected Behavior

Millennium should function as normal (minus update checking) when offline.

### Steps To Reproduce

1. Turn off wifi in windows settings. 

![Screenshot 2024-10-20 180939](https://github.com/user-attachments/assets/0d069a9f-a692-4773-a6d8-cfc522684922)

2. Launch steam. (I did it in dev mode using a shortcut: `"C:\Program Files (x86)\Steam\steam.exe" -cef-enable-debugging -dev`.)

3. Steam looks and acts like it does before installing Millennium.

### Operating System

Windows

### Anything else?

Logs: 

[debug.offline.log](https://github.com/user-attachments/files/17452235/debug.offline.log)

[debug.online.log](https://github.com/user-attachments/files/17452257/debug.online.log)

**Comment by AdamRaichu** [comment]
[debug.no_plugins.after_uninstall_and_reinstall.log](https://github.com/user-attachments/files/17452433/debug.log)

**Comment by shdwmtr** [comment]
I kept this open for a while, and it seems no one else has this issue, so I'm going to close it for now.
