### ISSUE TITLE
[Bug] Latest Steam update has seemingly broken the config UI for custom skins that have one

### ISSUE THREAD

**Issue by NathanL1370** [shdwmtr/millennium#157]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

Currently, if you attempt to open a custom skin's configuration screen in `Steam > Settings > Themes > Config icon`, an error message appears on skins like these:

Classic Steam Library:
![Screenshot 2024-11-06 101249](https://github.com/user-attachments/assets/70b3d4c1-600a-4f23-9ee4-44fe32f0bac3)
SpaceTheme for Steam:
![Screenshot 2024-11-06 101856](https://github.com/user-attachments/assets/be93dd35-76a7-4cd4-9aad-2eea2569b5cf)
Zehn:
![Screenshot 2024-11-06 101948](https://github.com/user-attachments/assets/3bbcfbff-acd9-4f52-ae60-c6ef23d16ce7)
Fluenty:
![Screenshot 2024-11-06 102020](https://github.com/user-attachments/assets/8ae04551-bfc6-4c11-bd6e-42fbb220472d)
Simple Dark:
![Screenshot 2024-11-06 102050](https://github.com/user-attachments/assets/dcafb1ee-47dd-4013-8dd7-da98bc78a64c)
Windows 95:
![Screenshot 2024-11-06 102126](https://github.com/user-attachments/assets/390346bf-cc43-4368-938d-dcdde07983d9)

### Expected Behavior

The config window should open, instead of an error reference appearing inside the main settings window.

### Steps To Reproduce

1) Install a theme that can be configured.

Skins that have a config screen:
- Classic Steam Library
- SpaceTheme For Steam
- Zehn
- Fluenty
- Simple Dark
- Windows 95

2) Open `Steam > Settings > Themes` and click the gear icon (Pencil icon in Zehn). An error reference should pop up inside the main settings window.

### Operating System

Windows

### Anything else?

This error prevents a prompt that requires Steam to reload from appearing in the settings window if you try to change the theme or toggle injections, unless you close it and reopen it.

This can also happen on Steam Deck (which is presumably Linux), but I can't say for other Linux distributions.
What's interesting for me is that Decky Loader also picks up on this error.
![Screenshot_20241106_104429](https://github.com/user-attachments/assets/5fd3cd40-f1d1-4bf3-8089-c56af35737b4)

Console output:
![Screenshot 2024-11-06 105913](https://github.com/user-attachments/assets/1eef9c06-90e7-40f8-baae-d4fbd1c94930)

**Comment by shdwmtr** [comment]
Thanks for the in depth report! I'll look into it!

**Comment by NathanL1370** [comment]
Looks like theme configuration UIs are fixed in the current release.

**Comment by shdwmtr** [comment]
Ah, yes; I forgot to close this!
