### ISSUE TITLE
[Bug] [Linux] Can't click dropdowns

### ISSUE THREAD

**Issue by Chorwacjen** [shdwmtr/millennium#158]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

When tapping on any of the buttons on the top of Steam (View, Friends, Games, "Steam", My profile on the right, etc.) no drop down menus show up. This struck me as weird. I thought it was the issue of my theme, but even after uninstalling it it still does not work. Although, the "View news from Steam" button DOES work for some reason, even though other ones refuse to work...

### Expected Behavior

Drop down menu shows up

### Steps To Reproduce

1. Open steam
2. Click on any of the top buttons

### Operating System

Linux

### Anything else?

Nothing shows up in the logs, except some errors repeated four times (not after one another) before all that:
``STEAM ERROR: unsafe call to unsetenv count:4 var:'__PYVENV_LAUNCHER__'``
the number after ``count`` is equal to which error is this.
There is also this overall:
```
STEAM ERROR: unsafe call to unsetenv count:1 var:'__PYVENV_LAUNCHER__'
STEAM Could not find platform independent libraries <prefix>
STEAM Could not find platform dependent libraries <exec_prefix>
STEAM ERROR: unsafe call to unsetenv count:2 var:'__PYVENV_LAUNCHER__'
```
and this:
``STEAM WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.``
I did not find any other errors in the log, and when clicking the menus no error shows up as I said.

**Comment by shdwmtr** [comment]
Does this issue occur when you run Steam without Millennium?

**Comment by Chorwacjen** [comment]
i dont know 100% because i didnt test but last time I played I believe I could since I would notice that in some form and I dont. At worst it has come in an issue in some new update today or yesterday but I will double check tomorrow. Still, I think this does not happen without millennium, but I need to confirm for sure

**Comment by Chorwacjen** [comment]
I don't understand at all - I reinstalled millennium, and it works, but now #119 is here again. The difference I see is that I launched it with the ``steam-millennium`` command when this (current) bug happened, but launched it with ``~/.millennium/start.sh`` when #119 happened, which by the way I do not absolutely understand where and how and why ``steam-millennium`` appeared and disappeared. I am lost completely in this, and I quite frankly do not understand a thing.

**Comment by shdwmtr** [comment]
steam-millennium isn't a command we supply, what is it?

**Comment by Chorwacjen** [comment]
hm, well i remember running some command other than the .sh file that I could manage themes, plugins etc. with

**Comment by shdwmtr** [comment]
oh, just `millennium`? That doesn't start steam though its just a CLI

**Comment by Chorwacjen** [comment]
but i remember running ``millennium start`` i think

**Comment by shdwmtr** [comment]
That isn't a sub command of the `millennium` CLI so I'm unsure how you launched it.

**Comment by Chorwacjen** [comment]
hmm, maybe im disremembering? either way, I launched a different way than the .sh file

**Comment by shdwmtr** [comment]
I would need to know how you launched it differently to diagnose the issue though

**Comment by Chorwacjen** [comment]
of course, i w

**Comment by Chorwacjen** [comment]
i will try finding out how i did it

**Comment by Chorwacjen** [comment]
I have absolutely, really no idea, now everything works fine. I will update if I find something wrong, but generally it seems to work all well now. Neither this nor #119 are, for some reason, present, and I will try to see in the coming days if I can find the core issue of the matter. Right now it's working so I'll close this.
