### ISSUE TITLE
[Bug] Trojan Wacatac.H!ml

### ISSUE THREAD

**Issue by MomBon** [shdwmtr/millennium#162]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

The latest update 2.14.1 has caused my pc to flag Millenium as a virus now with the virus labeled on the above title.

I reinstalled the latest version and got this flag again, I don't get this on previous versions, only this one.
![warning](https://github.com/user-attachments/assets/22c71af6-3228-4187-bbe5-39a19692f0a2)

### Expected Behavior

Not get flagged by a virus

### Steps To Reproduce

Install the latest version

### Operating System

Windows

### Anything else?

The fact that previous versions didn't have this issue until now, I won't be using this until this issue gets fixed.

**Comment by shdwmtr** [comment]
Its a false positive. "ml" at the end of the detection means machine learning, which is making a mistake in this case. I can't address it as I'm not a Microsoft employee. A general rule of thumb is to use your brain and not rely on an antivirus, which usually heuristically generates reports that aren't accurate to what the software does. 

Keep in mind you opened an issue about virus detection on an open source program, you can see absolutely everything Millennium does, down to the smallest bit manipulation.
