### ISSUE TITLE
[Bug]Trojan

### ISSUE THREAD

**Issue by Solarity991** [shdwmtr/millennium#163]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

I noticed that my steam wasn't skinned today and that a trojan warning came up from windows defender. I didn't think much of it until I tried installing Millennium again. Once it was installed, I had received the same message as I had gotten prior. I took the latest release and ran it through virus total and it to came back with a warning that there was a trojan detected. It's a real shame as I really do enjoy using Millenium. 
![Trojan1](https://github.com/user-attachments/assets/d929a24a-e16c-4074-98ee-bd8e04f1cc70)
[millennium-v2.14.1-windows-x86_64.zip](https://github.com/user-attachments/files/17690554/millennium-v2.14.1-windows-x86_64.zip)
[https://www.virustotal.com/gui/file/5d90138c22c6bf3a17f9f3de57a610bffce0f3c2e827420be0c9fcff3a3471e4](url)

### Expected Behavior

To not have a trojan in it

### Steps To Reproduce

1. Install it
2. See what windows defender says

### Operating System

Windows

### Anything else?

![Trojan1](https://github.com/user-attachments/assets/e325ce1e-6d9c-475b-a025-7674da91037d)
[https://www.virustotal.com/gui/file/5d90138c22c6bf3a17f9f3de57a610bffce0f3c2e827420be0c9fcff3a3471e4](url)
[millennium-v2.14.1-windows-x86_64.zip](https://github.com/user-attachments/files/17690558/millennium-v2.14.1-windows-x86_64.zip)

**Comment by shdwmtr** [comment]
It's a false positive, I'm experimenting with solutions on how to prevent it from happening. Rest assured there is nothing to worry about, Millennium is open source, you can see what it does.

**Comment by Solarity991** [comment]
> It's a false positive, I'm experimenting with solutions on how to prevent it from happening. Rest assured there is nothing to worry about, Millennium is open source, you can see what it does.

I hope so, the user32.dll is the one that's being flagged as a trojan

**Comment by shdwmtr** [comment]
@Solarity991 There is no need to "hope", it is a false positive. I am confident Millennium does not do anything malicious. You can review the source code at your leisure.
