### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by peso300bars** [shdwmtr/millennium#164]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

![image](https://github.com/user-attachments/assets/0ce8d1ce-fcad-4f44-9d32-7e745b6ab3c9)

### Expected Behavior

еще при загрузке темы вечная загрузка и не устанавливается тема

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/6e07ff08-6c31-431f-9b97-41294845b090)

### Operating System

Windows

**Comment by shdwmtr** [comment]
fixed!
