### ISSUE TITLE
[Bug] Connection handler failed when using the website

### ISSUE THREAD

**Issue by eiieieeieieiieeiee** [shdwmtr/millennium#165]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

Every time i select theme on the website it causes this error to occur 
![Capture](https://github.com/user-attachments/assets/997ac72c-3d45-423c-994e-a7eba3fb4af8)
and when i try to download a theme it gets stuck on this
![image](https://github.com/user-attachments/assets/943033c4-a0eb-483e-bad2-fccf6088c8b2)

### Expected Behavior

to be able to download and use a theme

### Steps To Reproduce

1. open the website
2. go to the themes tab
3. and click on a theme

### Operating System

Windows

**Comment by eiieieeieieiieeiee** [comment]
ive unintalled and reinstalled but nothing seems to fix it

**Comment by shdwmtr** [comment]
Fixed! It will be in the next update stay tuned.
