### ISSUE TITLE
[Bug] Windows Defender flags "User32.dll" as a malicious file. No matter the amount of times I've "allowed" it.

### ISSUE THREAD

**Issue by LaggyAsBalls** [shdwmtr/millennium#166]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

![image](https://github.com/user-attachments/assets/eb89bbb7-c4e6-4d92-909a-f9577f21506f)

Every time Steam opens with Millennium installed, or more-over on every reboot it flags "User32.dll" as malicious. I cannot simply just "allow it" because it flags user32.dll every time I open up Steam or reboot the computer. As you can see in the picture below, the amount of times Windows as detected User32.dll as malicious. 

![image](https://github.com/user-attachments/assets/01182301-f6b0-4dfc-b905-f030ca9cc3e5)

### Expected Behavior

I expect Steam to open with Millennium installed, rather it opens steam normally because User32.dll is missing.

### Steps To Reproduce

1. Have Windows Defender on
2. Open Steam with Millennium installed
2b. Or reboot the computer
3. Windows will flag it as malicious.

### Operating System

Windows

### Anything else?

This can POSSIBLY be fixed simply by changing the checksum of user32.dll and then checking that file with [virustotal.](https://www.virustotal.com/gui/home/upload)

I have indeed have seen other people talk about this issue and I believe that person has been dismissive of this issue. This is very, very annoying.

**Comment by shdwmtr** [comment]
It appears you aren't using the latest version of Millennium, this issue was recently resolved (hopefully)

**Comment by shdwmtr** [comment]
Closing for no response
