### ISSUE TITLE
[Bug] "Inject stylesheets" option description is duplicated for "inject javascript" option description.

### ISSUE THREAD

**Issue by kotenok2000** [shdwmtr/millennium#168]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

When i looked at theme settings i have noticed that "Inject stylesheets" option description is duplicated for "inject javascript" option description.

### Expected Behavior

"Inject javascript" option description is different from "Inject stylesheets" option description.

### Steps To Reproduce

1. Start steam with millennium Millennium@v2.15.0.
2. open settings.
3. Open Themes  menu.

### Operating System

Windows

### Anything else?

![image](https://github.com/user-attachments/assets/f9603fad-df6b-4ee9-b7b9-a42d4a440ac3)
Steam Beta Branch:  Stable Client
Steam Version:  1731433018
Steam Client Build Date:  Tue, Nov 12 8:10 PM UTC -08:00
Steam Web Build Date:  Tue, Nov 12 5:03 AM UTC -08:00
Steam API Version:  SteamClient021

**Comment by shdwmtr** [comment]
Oops, you're right. I must have mixed up the English locales.
