### ISSUE TITLE
[Bug] Downloading in PowerShell

### ISSUE THREAD

**Issue by DEA1HYT** [shdwmtr/millennium#175]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [x] My issue is not caused by a plugin

### Describe the Bug

What the hell is this??
![Screenshot 2024-12-01 100133](https://github.com/user-attachments/assets/bd6e0fbb-7ac2-46e8-a80f-96c5d959731d)

### Expected Behavior

It would work, and everything would be good and i would get my old steam ui.

### Steps To Reproduce

1. Opened PowerShell, 2. Inserted script "iwr -useb "https://steambrew.app/install.ps1" | iex" 3. Saw the message.

### Operating System

Windows

### Anything else?

Not really anything else.

**Comment by shdwmtr** [comment]
You should be good regardless, it already installed. Just start steam
