### ISSUE TITLE
[Bug] Steam hogging localhost:8080

### ISSUE THREAD

**Issue by infernus-b** [shdwmtr/millennium#177]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

For some reason, whenever steam is open, it will start using localhost:8080?
![zen_kRVhQjCLaf](https://github.com/user-attachments/assets/44a80603-8a36-4bde-b4f5-806b94127d70)

### Expected Behavior

port 8080 being open

### Steps To Reproduce

1. install millennium
2. goto localhost:8080

### Operating System

Windows

### Anything else?

![steamwebhelper_j5R2pDjyDB](https://github.com/user-attachments/assets/45a1491c-9beb-4f3b-9a0e-8d576e0c857f)
not sure if this will help

**Comment by madmaxgrey** [comment]
not sure what the issue is Millennium uses port 8080 for stuff to work

**Comment by madmaxgrey** [comment]
this is intended

**Comment by infernus-b** [comment]
oh I'm sorry, I wasn't aware of this information

**Comment by shdwmtr** [comment]
This is information millennium makes Steam expose so it can interact with portions of the client without modifying memory. It will have to use a port for it to work, but it doesn't *half* to be 8080.
