### ISSUE TITLE
[Bug] Another app using port 8080

### ISSUE THREAD

**Issue by awentivzera** [shdwmtr/millennium#179]
### Before Reporting

- [x] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

![photo_2024-12-11_16-25-13](https://github.com/user-attachments/assets/05b64d45-83a0-4e53-b585-9d2fbab61d6b)

### Expected Behavior

I do not know how to solve my problem, I searched all the forums, and found only one solution, it did not help, what else can I try

### Steps To Reproduce

I was installing a theme for steam according to the guide, but I get a fatal error

### Operating System

Windows

**Comment by shdwmtr** [comment]
Unless you can provide information on what you tried, and how it didn't work, we can't really do much to help.

I assume it has been solved as we haven't heard from you.
