### ISSUE TITLE
[bug]failed to load millennium.dll

### ISSUE THREAD

**Issue by YCZ01111** [shdwmtr/millennium#188]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

![IMG_0969](https://github.com/user-attachments/assets/6735940c-1ef3-4cf0-9a4c-b3f0d9176121)

### Expected Behavior

Successful start

### Steps To Reproduce

start steam

### Operating System

Windows

### Anything else?

win10

**Comment by shdwmtr** [comment]
Must have been deleted by an antivirus.
