### ISSUE TITLE
[Feature] NixOS specific patch in documentation

### ISSUE THREAD

**Issue by Encoded14** [shdwmtr/millennium#192]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

Since Nix-OS works a bit different from "regular" Linux distributions it errors with the following:

`steam.sh[574114]: Running Steam on nixos 25.05 64-bit
steam.sh[574114]: STEAM_RUNTIME is enabled automatically
setup.sh[574150]: Steam runtime environment up-to-date!
Could not start dynamically linked executable: steam-runtime-identify-library-abi
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
run.sh[574162]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
run.sh[574162]: Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 127
steam.sh[574114]: Logging to console-linux.txt disabled via STEAM_RUNTIME_LOGGER
steam.sh[574114]: Error: You are missing the following 32-bit libraries, and Steam may not run:
libc.so.6
mktemp: /home/linus/.steam/steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libattr.so.1: version `ATTR_1.3' not found (required by mktemp)
Error:
cat: /home/linus/.steam/steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libattr.so.1: version `ATTR_1.3' not found (required by cat)
^C`

The quickest way to get millennium working with nixos is to add "steam-run" in start.sh

`bash steam-run ~/.steam/steam/steam.sh > >(steam_output) 2>&1 "$@"`

I am not sure if there is a better way to do it that doesn't require steam-run to be installed.

**Comment by shdwmtr** [comment]
Documentation is [here](https://github.com/shdwmtr/steambrew/blob/main/docs/ui/users/installing.md), you're welcome to PR!
