### ISSUE TITLE
[Bug] Cloudflare challenge always fails since 2.16.0, fully blocking certain pages

### ISSUE THREAD

**Issue by tddebart** [shdwmtr/millennium#194]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

Since recently cloudflare has updated something on their end that makes it so that their security challenge fails in the steam browser when millennium is installed. This is likely because of the script tags that get added by millennium which triggers their bot detection. 
In 2.15 and vanilla steam it all works fine because nothing is injected into the webkit context but since 2.16 and some changes at cloudflare certain websites just block you from accessing them.
I have tested this on a clean installation of steam and millennium.

### Expected Behavior

For the websites to load and not throw an error page

### Steps To Reproduce

1. Middle mouse on any link in the steam store to open the steam browser
2. Go to a site with a Cloudflare challenge, like:
    https://steamdb.info/
    https://2captcha.com/demo/cloudflare-turnstile-challenge
    https://ashesofcreation.com/api/auth/signup
    Or any page that uses an Cloudflare challenge.
3. Observe that after clicking the checkbox it goes to an _error or blank page

### Operating System

Windows

### Anything else?

Here is also an video which was provided to me in this issue https://github.com/tddebart/Steam-SteamDB-extension/issues/9

https://github.com/user-attachments/assets/fdda15e4-e95a-4220-839f-36a22ef30750

**Comment by glitchchh** [comment]
Ja

BossSloth ***@***.***> schrieb am Di. 24. Dez. 2024 um 13:23:

**Comment by shdwmtr** [comment]
Give this build a go:

https://github.com/shdwmtr/millennium/actions/workflows/artifact.yml

**Comment by tddebart** [comment]
Seems to have fully fixed this issue but also seems to have introduced a new one.
On first load of the webkit context after boot (or after a client refresh) is seems to fail the websocket connection and so no webkit js get's loaded in meaning plugins don't work. But after a refresh it all just works. It is just the first load and it error with this error:
<details>
<summary>

`Refused to connect to 'ws://localhost:61928/' because it violates the following Content Security Policy directive: "connect-src 'self' http://store.steampowered.com`

</summary>

`Refused to connect to 'ws://localhost:61928/' because it violates the following Content Security Policy directive: "connect-src 'self' http://store.steampowered.com https://store.steampowered.com http://127.0.0.1:27060 ws://127.0.0.1:27060 https://community.fastly.steamstatic.com/ https://steamcommunity.com/ https://steamcommunity.com/ wss://community.steam-api.com/websocket/ https://api.steampowered.com/ https://login.steampowered.com/ https://help.steampowered.com/ https://steam.tv/ https://shared.fastly.steamstatic.com/ https://checkout.steampowered.com/ https://*.steamstatic.com https://*.steamcontent.com https://*.valvesoftware.com https://*.steambeta.net https://*.discovery.beta.steamserver.net https://*.cqloud.com https://steambroadcast.akamaized.net https://steambroadcast-test.akamaized.net https://broadcast.st.dl.eccdnx.com https://lv.queniujq.cn https://steambroadcastchat.akamaized.net https://api.steampowered.com https://steamvideo-a.akamaihd.net https://video.st.dl.eccdnx.com https://vd.queniujq.cn https://*.storage.googleapis.com https://sketchfab.com".`
</details>

Should I make a new issue for this?

**Comment by shdwmtr** [comment]
I forgot to update one of Millenniums libs on the build.

this build fixes it:
https://github.com/shdwmtr/millennium/actions/runs/12524389759

**Comment by shdwmtr** [comment]
Perfect.

**Comment by Exabits1** [comment]
This issue seems to have returned on v.3.0.0-beta.21 and above. I'm unable pass the turnstile on https://steamdb.info/ and https://2captcha.com/demo/cloudflare-turnstile-challenge. At least one other person has reported the same behavior BossSloth/Extendium#89

**Comment by MisterFunkee** [comment]
> This issue seems to have returned on v.3.0.0-beta.21 and above. I'm unable pass the turnstile on https://steamdb.info/ and https://2captcha.com/demo/cloudflare-turnstile-challenge. At least one other person has reported the same behavior [BossSloth/Extendium#89](https://github.com/BossSloth/Extendium/issues/89)

Correct, same here...

<img width="2755" height="1845" alt="Image" src="https://github.com/user-attachments/assets/a06430f4-9af0-4af3-beed-c77740c1b9ac" />

**Comment by ertup0** [comment]
this issue should be definitely reopened, any site that uses cloudflare captchas are unusable with millenium installed

**Comment by MisterFunkee** [comment]
> this issue should be definitely reopened, any site that uses cloudflare captchas are unusable with millenium installed

+1 

still persists in newest Millenium version. 3.1

It was so much better before the Extendium nonsense...

**Comment by AzaelMew** [comment]
Issues still presists on v3.2.1 beta-1
