### ISSUE TITLE
[Bug] A fatal error that now prevents Steam from starting

### ISSUE THREAD

**Issue by Sevvlaser** [shdwmtr/millennium#195]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [ ] My issue is not caused by a plugin

### Describe the Bug

I wanted to switch to another account to check how the skins look there, an error appeared. I checked everything according to the manual, but I still didn't understand what the problem was. The strange thing is that when changing the skin, you need to restart Steam, but the error did not appear.

![Screenshot_1](https://github.com/user-attachments/assets/fd4b4a2c-6e0a-4620-a145-b855d7142bb9)
The error that appeared

![Screenshot_2](https://github.com/user-attachments/assets/1c298980-e367-4a64-a272-4a3361a8df15)
The result of searching for a conflicting application using PowerShell

![Screenshot_3](https://github.com/user-attachments/assets/9b8b2631-c554-4eed-92d9-1f88ce83eebe)

### Expected Behavior

Steam will run without any problems.

### Steps To Reproduce

1. Understand what exactly is causing the error
2. Find a way to fix the error

### Operating System

Windows

**Comment by shdwmtr** [comment]
Does this consistently happen when you start Steam?

**Comment by shdwmtr** [comment]
Closing for no response
