### ISSUE TITLE
[Feature] Custom theme options tabs

### ISSUE THREAD

**Issue by SpaceEnergy** [shdwmtr/millennium#93]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

Custom tabs that the dev can create for the theme options to make many theme options look a little bit more organized and tidy

like this:
![image](https://github.com/user-attachments/assets/1a56a6a1-9840-4419-a894-b200f128aa60)

**Comment by shdwmtr** [comment]
Suggest a `skin.json` formatting you'd like to see it use.

**Comment by SpaceEnergy** [comment]
```json
{
    "Conditions": {
        "Tab name 1": {
            "Experimental": {
                "description": "Activates experimental functions (there may/will be bugs)",
                "default": "no",
                "values": {
                    "no": {},
                    "yes": {
                        "TargetCss": { "affects": ["^Steam$"], "src": "options/experimental.css" },
                        "TargetJs": { "affects": ["^Steam$"], "src": "options/experimental.js" }
                    }
                }
            }
        },
        "Tab name 2": {
            "Experimental": {
                "description": "Activates experimental functions (there may/will be bugs)",
                "default": "no",
                "values": {
                    "no": {},
                    "yes": {
                        "TargetCss": { "affects": ["^Steam$"], "src": "options/experimental.css" },
                        "TargetJs": { "affects": ["^Steam$"], "src": "options/experimental.js" }
                    }
                }
            }
        }
    }
}
```

**Comment by SpaceEnergy** [comment]
@shdwmtr @ricewind012 could you add something that if a tab is called “Colors” it is simply added to the tab with the root colors

**Comment by ricewind012** [comment]
i don't get it

**Comment by SpaceEnergy** [comment]
I give an option in the skin.json file `"tab": "Color"` or `"tab": "color"` and this is then added to the top of this tab:
![image](https://github.com/user-attachments/assets/ae60ab6e-b834-4c17-bd3a-2367bffb6198)

**Comment by shdwmtr** [comment]
@SpaceEnergy Provide your skin.json, I'm relatively sure @ricewind012 doesn't even know that exists

**Comment by SpaceEnergy** [comment]
@ricewind012 
das: https://github.com/SpaceTheme/Steam/blob/main/skin.json#L117 wird zu einem color tab gemacht und meine frage ist nun das wenn man in einer eigenen option beim Tab namen "Colors"/"colors" eingibt das es auch in dem tab kommt wie RootColors

like this:
```json
"System accent colors": {
            "description": "Replaces the SpaceTheme accent colors with your system accent colors",
            "default": "no",
            *"tab": "Colors"*,
            "values": {
                "no": {},
                "yes": {
                    "TargetCss": { "affects": [".*"], "src": "options/systemAccent.css" }
                }
            }
        }
```
![image](https://github.com/user-attachments/assets/72e2d781-6e92-4af3-b91b-52da3bd1ae06)

**Comment by SpaceEnergy** [comment]
no that's not the problem xd
but root-colors creates a “Colors” tab and when i assign the tab “Colors” to an option a 2nd tab with the name is created and not made in the already existing one

**Comment by shdwmtr** [comment]
@SpaceEnergy is this solved?

**Comment by SpaceEnergy** [comment]
in itself already, but I would still be happy if that still comes that if you give an option the tab name Colors that it comes with in the Colors tab so where you can set the root colors (because currently an extra tab would be created)

If this is better for you I can open an extra issue for this feature

**Comment by shdwmtr** [comment]
Yeah open another issue and go more into detail for documentation purposes.
